version: "3.9"

services:
  apilocal:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MONGO_HOST: "mongodb://db:27017" 
      MONGO_DB: "my_app_sv"
      PASSWORD_ADMIN: "tino2673"
      SERVER_PORT: 5000
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
